spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.abwvjbp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: ContactManger

server:
  port: 8080
  servlet:
        context-path: /contact-manager
